### ISSUE TITLE
[request]Please support Petalinux 2019.1

### ISSUE THREAD

**Issue by nvl1109** [Xilinx/Edge-AI-Platform-Tutorials#22]
Hi,
I'm using Petalinux 2019.1 for our system. But the DPU-integration library (https://github.com/Xilinx/Edge-AI-Platform-Tutorials/tree/master/docs/DPU-Integration/reference-files/files/recipes-apps/dnndk/files/lib/libdputils.so.3.3) requires OpenCV 3.3, but Petalinux 2019.1 uses OpenCV 3.4. So I got compile error.
Please upgrade the repository to support Petalinux 2019.1. Thank you so much.

**Comment by pedrombmachado** [comment]
Have you tried to create symbolic links to the missing so? 
Check [here](https://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work)

**Comment by nvl1109** [comment]
The newest TRD release supports Petalinux 2019.1 :)
