### ISSUE TITLE
Error creating a custom DPU project

### ISSUE THREAD

**Issue by pedrombmachado** [Xilinx/Edge-AI-Platform-Tutorials#38]
Dear Xilinx team,
  I am building a custom DPU for our boards [https://github.com/SundanceMultiprocessorTechnology/VCS-1](url) and I am not able to complete the following steps in **Step 5: Configure the rootfs**

> Apps ->

>    autostart

Reason: Option Not available

> Modules ->

 > - dpu

Reason: Option Not available

>User Packages ->

 > - dnndk

Reason: Option Not available

Please note that I completed all the steps before without any problem.

**Comment by jack-sundance** [comment]
I am having the same issue, I cannot go any further as i cannot enable or disable the packages.

**Comment by pedrombmachado** [comment]
@jack-sundance ,
Solution can be found [here](https://forums.xilinx.com/t5/Machine-Learning/Error-creating-a-custom-DPU-project/m-p/1032139#M2391).
edit _petalinux-image-full.bbappend_ and add the recipies here.
```
$ nano project-spec/meta-user/recipes-core/images/petalinux-image-full.bbappend
```
