### ISSUE TITLE
Performance comparison with other edge devices 

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [Xilinx/Edge-AI-Platform-Tutorials#8]
Hi, 

Do we have any performance comparison between the other edge module with this, maybe google coral edge or with jetson platform. 

This will help to make a decision and try out these kits. 

Best Regards
 SSH

**Comment by jcory-xilinx** [comment]
This tutorial walks through an un-pruned version of SSD using 300x300 as the input size.  You should see around >20 FPS of performance on a ZU9 (ZCU102) device if video resizing is not included which is around a 15W device.  With pruning, we are able to achieve around 120 FPS on a ZU9 device with the 480x360 SSD model which is more compute intensive.  A TX2 GPU should achieve around 10-15 FPS for the 480x360 SSD model.

**Comment by ShettyHarapanahalli** [comment]
Thanks for sharing this information.
